### ISSUE TITLE
ECONNREFUSED

### ISSUE THREAD

**Issue by obsid-tr** [bigbeartechworld/big-bear-umbrel#6]
Hello,
I'd like to come back to you regarding access to the service.
Here is the error I have in the logs:

`big-bear-umbrel-ghost

Attaching to big-bear-umbrel-ghost_db_1, big-bear-umbrel-ghost_server_1, big-bear-umbrel-ghost_app_proxy_1, big-bear-umbrel-ghost_tor_server_1
app_proxy_1   | [HPM] Proxy created: /  -> http://big-bear-umbrel-ghost_server_1:2368
app_proxy_1   | Waiting for big-bear-umbrel-ghost_server_1:2368 to open...
app_proxy_1   | Ghost is now ready...
app_proxy_1   | Listening on port: 7205
app_proxy_1   | [HPM] Error occurred while proxying request 192.168.1.90:7205/ to http://big-bear-umbrel-ghost_server_1:2368/ [ECONNREFUSED] (https://nodejs.org/api/errors.html#errors_common_system_errors)
app_proxy_1   | [HPM] Error occurred while proxying request 192.168.1.90:7205/ghost to http://big-bear-umbrel-ghost_server_1:2368/ [ECONNREFUSED] (https://nodejs.org/api/errors.html#errors_common_system_errors)
app_proxy_1   | [HPM] Error occurred while proxying request 192.168.1.90:7205/ghost to http://big-bear-umbrel-ghost_server_1:2368/ [ECONNREFUSED] (https://nodejs.org/api/errors.html#errors_common_system_errors)
app_proxy_1   | [HPM] Error occurred while proxying request 192.168.1.90:7205/ghost to http://big-bear-umbrel-ghost_server_1:2368/ [ECONNREFUSED] (https://nodejs.org/api/errors.html#errors_common_system_errors)
app_proxy_1   | [HPM] Error occurred while proxying request 192.168.1.90:7205/ to http://big-bear-umbrel-ghost_server_1:2368/ [ENOTFOUND] (https://nodejs.org/api/errors.html#errors_common_system_errors)
app_proxy_1   | [HPM] Error occurred while proxying request 192.168.1.90:7205/ to http://big-bear-umbrel-ghost_server_1:2368/ [ECONNREFUSED] (https://nodejs.org/api/errors.html#errors_common_system_errors)
db_1          | 
db_1          | 2023-09-02T07:26:21.823068Z 0 [Warning] [MY-011068] [Server] The syntax '--skip-host-cache' is deprecated and will be removed in a future release. Please use SET GLOBAL host_cache_size=0 instead.
db_1          | 2023-09-02T07:26:21.828729Z 0 [System] [MY-010116] [Server] /usr/sbin/mysqld (mysqld 8.0.34) starting as process 1
db_1          | 2023-09-02T07:26:21.854398Z 1 [System] [MY-013576] [InnoDB] InnoDB initialization has started.
db_1          | 2023-09-02T07:26:23.043224Z 1 [System] [MY-013577] [InnoDB] InnoDB initialization has ended.
db_1          | 2023-09-02T07:26:23.974680Z 0 [Warning] [MY-010068] [Server] CA certificate ca.pem is self signed.
db_1          | 2023-09-02T07:26:23.975335Z 0 [System] [MY-013602] [Server] Channel mysql_main configured to support TLS. Encrypted connections are now supported for this channel.
db_1          | 2023-09-02T07:26:23.980686Z 0 [Warning] [MY-011810] [Server] Insecure configuration for --pid-file: Location '/var/run/mysqld' in the path is accessible to all OS users. Consider choosing a different directory.
db_1          | 2023-09-02T07:26:24.129401Z 0 [System] [MY-011323] [Server] X Plugin ready for connections. Bind-address: '::' port: 33060, socket: /var/run/mysqld/mysqlx.sock
db_1          | 2023-09-02T07:26:24.130635Z 0 [System] [MY-010931] [Server] /usr/sbin/mysqld: ready for connections. Version: '8.0.34'  socket: '/var/run/mysqld/mysqld.sock'  port: 3306  MySQL Community Server - GPL.
server_1      | [2023-09-02 07:27:25] INFO Creating table: collections
server_1      | [2023-09-02 07:27:25] INFO Creating table: collections_posts
server_1      | [2023-09-02 07:27:26] INFO Model: Collection
server_1      | [2023-09-02 07:27:26] INFO Model: Product
server_1      | [2023-09-02 07:27:26] INFO Model: Newsletter
server_1      | [2023-09-02 07:27:26] INFO Model: Tag
server_1      | [2023-09-02 07:27:27] INFO Model: Permission
server_1      | [2023-09-02 07:27:30] INFO Model: Post
server_1      | [2023-09-02 07:27:33] INFO Model: Integration
server_1      | [2023-09-02 07:27:34] INFO Relation: Role to Permission`

How can I solve it?
Thanks

**Comment by dragonfire1119** [comment]
The error says that the proxy cannot connect to the `big-bear-umbrel-ghost_server_1`. So you would need to find out if that container is running and if so give me the logs.

List the running containers:

First, you'll want to list all the running containers to identify the container ID for big-bear-umbrel-ghost_server_1.

```bash
docker ps
```

Retrieve the logs:

Once you have the container ID for big-bear-umbrel-ghost_server_1, you can use the docker logs command to retrieve its logs.

```bash
docker logs [container id]
```

Replace [container id] with the actual ID from the previous step.

**Comment by fluckx** [comment]
I had the same issue as above. In my case it just resolved itself.
It takes some time for the ghost container to come through. I restarted the container once though.

The umbrel logs looks like this
```
# big-bear-umbrel-ghost_app_proxy_1
Error waiting for port: "The address 'big-bear-umbrel-ghost_server_1' cannot be found"
Retrying...
Error waiting for port: "The address 'big-bear-umbrel-ghost_server_1' cannot be found"
Retrying...
Error waiting for port: "The address 'big-bear-umbrel-ghost_server_1' cannot be found"
Retrying...
Error waiting for port: "The address 'big-bear-umbrel-ghost_server_1' cannot be found"
Retrying...
Error waiting for port: "The address 'big-bear-umbrel-ghost_server_1' cannot be found"
Retrying...
Ghost is now ready...
Listening on port: 7205
```

Eventually it came through ( last two lines ). At which point I end up at a maintenance landing page.

```
We'll be right back.
We're busy updating our site to give you the best experience, and will be back soon.
```

The ghost server logs look like this:

```
# big-bear-umbrel-ghost_server_1

[2024-04-11 22:14:12] INFO Ghost is running in production...
[2024-04-11 22:14:12] INFO Your site is now available on http://192.168.50.155:7205/
[2024-04-11 22:14:12] INFO Ctrl+C to shut down
[2024-04-11 22:14:12] INFO Ghost server started in 0.576s
[2024-04-11 22:14:12] INFO Database is in a ready state.
[2024-04-11 22:14:12] INFO Ghost database ready in 0.774s
[2024-04-11 22:14:13] WARN Missing mail.from config, falling back to a generated email address. Please update your config file and set a valid from address
[2024-04-11 22:14:13] ERROR Unhandled rejection: Access denied for user 'ghost'@'10.21.0.8' (using password: YES)
Access denied for user 'ghost'@'10.21.0.8' (using password: YES)
Error Code: 
    ER_ACCESS_DENIED_ERROR
----------------------------------------
Error: Access denied for user 'ghost'@'10.21.0.8' (using password: YES)
    at Packet.asError (/var/lib/ghost/versions/5.82.1/node_modules/mysql2/lib/packets/packet.js:728:17)
    at ClientHandshake.execute (/var/lib/ghost/versions/5.82.1/node_modules/mysql2/lib/commands/command.js:29:26)
    at Connection.handlePacket (/var/lib/ghost/versions/5.82.1/node_modules/mysql2/lib/connection.js:481:34)
    at PacketParser.onPacket (/var/lib/ghost/versions/5.82.1/node_modules/mysql2/lib/connection.js:97:12)
    at PacketParser.executeStart (/var/lib/ghost/versions/5.82.1/node_modules/mysql2/lib/packet_parser.js:75:16)
    at Socket.<anonymous> (/var/lib/ghost/versions/5.82.1/node_modules/mysql2/lib/connection.js:104:25)
    at Socket.emit (node:events:517:28)
    at addChunk (node:internal/streams/readable:368:12)
    at readableAddChunk (node:internal/streams/readable:341:9)
    at Readable.push (node:internal/streams/readable:278:10)
    at TCP.onStreamRead (node:internal/stream_base_commons:190:23)
[2024-04-11 22:14:15] INFO Adding offloaded job to the queue
[2024-04-11 22:14:15] INFO Scheduling job mentions-email-report at 17 53 * * * *. Next run on: Thu Apr 11 2024 22:53:17 GMT+0000 (Coordinated Universal Time)
[2024-04-11 22:14:15] INFO Adding one-off job to queue with current length = 0 called 'members-migrations'
[2024-04-11 22:14:15] INFO Stripe not configured - skipping migrations
[2024-04-11 22:14:16] INFO Adding offloaded job to the queue
[2024-04-11 22:14:16] INFO Scheduling job clean-expired-comped at 20 13 0 * * *. Next run on: Fri Apr 12 2024 00:13:20 GMT+0000 (Coordinated Universal Time)
[2024-04-11 22:14:16] INFO Adding offloaded job to the queue
[2024-04-11 22:14:16] INFO Scheduling job clean-tokens at 58 8 5 * * *. Next run on: Fri Apr 12 2024 05:08:58 GMT+0000 (Coordinated Universal Time)
[2024-04-11 22:14:16] INFO Ghost booted in 4.359s
[2024-04-11 22:14:16] INFO Adding offloaded job to the queue
[2024-04-11 22:14:16] INFO Scheduling job update-check at 58 55 0 * * *. Next run on: Fri Apr 12 2024 00:55:58 GMT+0000 (Coordinated Universal Time)
[2024-04-11 22:14:16] INFO Running milestone emails job on Thu Apr 11 2024 22:14:16 GMT+0000 (Coordinated Universal Time)
[2024-04-11 22:16:55] INFO [Recommendations] Updating recommendations metadata
```

I'm not sure why it is trying to connect to `10.21.0.8` as that is not the IP of the database, but the IP of the container itself ( localhost ). 

The environment variables are set:
```
database__connection__host=db
database__connection__database=ghost
```

nslookup resolves `db` as the database container too

```
79bbb974d027:/var/lib/ghost# nslookup db
Server:         127.0.0.11
Address:        127.0.0.11:53

Non-authoritative answer:

Non-authoritative answer:
Name:   db
Address: 10.21.0.7
Name:   db
Address: 10.21.0.4
```

the 10.21.0.4 address is not assigned to a pod unassigned. Not sure where that comes from.
My issue now is that I'm stuck on the `we'll be back page`. I should open a different issue for that probably :).
Hope the debug info helps.

This is on an Umbrel Home ( 2024 ) -- umbrelOS 1.0.4
